# Generated by Django 5.1.3 on 2024-12-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_alter_profesor_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
