# Generated by Django 5.1.3 on 2024-12-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='blog/portadas/'),
        ),
    ]
