# Generated by Django 5.1.3 on 2024-12-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_publicacion_imagen_portada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
